.\" Manpage for prueba.
.\" Contact alvdegar2@alum.us.es in order to correct errors or typos
.TH man 8 "05 december 2022" "0.1" "prueba man page"
.SH NAME
prueba \- Ejecuta un script de prueba
.SH SYNOPSIS
prueba (No admite opciones extra)
.SH DESCRIPTION
prueba es un programa escrito en C que, en caso de haber sido correctamente instalado, imprime por pantalla un mensaje.
.SH OPTIONS
Este programa no toma ninguna opción.
.SH BUGS
No hay bugs conocidos.
.SH AUTHOR
Álvaro de Castro García (alvdegar2@alum.us.es)
